-- Create irrigation_logs table
create table public.irrigation_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  action text not null, -- 'START' or 'STOP'
  duration integer, -- in seconds
  water_used float, -- in liters
  details jsonb -- extra info like flow rate etc
);

-- Create robot_logs table
create table public.robot_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  robot_id text not null, -- 'roomba_j7' or 'braava_jet'
  action text not null, -- 'START', 'STOP', 'DOCK', 'ERROR', 'STATUS'
  status text, -- 'cleaning', 'idle', 'error'
  details jsonb -- battery, bin status, etc
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table public.irrigation_logs enable row level security;
alter table public.robot_logs enable row level security;

-- Create policies (Allow read access for anon, write access for service role only)
-- Anon (Public) can read
create policy "Public logs are viewable by everyone"
  on public.irrigation_logs for select
  using ( true );

create policy "Public logs are viewable by everyone"
  on public.robot_logs for select
  using ( true );

-- Service Role can do everything (implicit, but good to know)
-- We don't need explicit policies for service_role as it bypasses RLS, 
-- but we should ensure Anon cannot write.
